generator:
    latent_dim:
        2
    reshape:
        [7, 7, 128]
    filters:
        [128, 128, 1]
    kernel_sizes:
        [4, 4, 7]
    activations:
        ['linear', 'linear', 'sigmoid']
    strides:
        [2, 2, 1]
discriminator:
    input_shape:
        [28, 28, 1]
    filters:
        [64, 64]
    kernel_sizes:
        [3, 3]
    activations:
        ['linear', 'linear']
    strides:
        [2, 2]