encoder:
    filters:
        [32, 64, 32]
    kernel_sizes:
        [3, 3, 3]
    activations:
        ['relu', 'relu', 'relu']
    strides:
        [2, 2, 2]
    latent_dim:
        2
    input_shape:
        [28, 28, 1]
decoder:
    filters:
        [64, 32, 1]
    kernel_sizes:
        [3, 3, 3]
    activations:
        ['relu', 'relu', 'sigmoid']
    strides:
        [2, 2, 1]
    latent_dim:
        2
    reshape:
        [7, 7, 64]